### ISSUE TITLE
Local Translation Offset seems to do nothing

### ISSUE THREAD

**Issue by ababak** [mmerchante/instanceAlongCurve#4]
First of all I'd like to thank you for the brilliant plugin!
I can't figure out how to use Offsets > Local Translation Offset. It doesn't work for me, whatever values I use. Is there a bug or am I missing something?

**Comment by mmerchante** [comment]
Hi ababak,

Can you send me an example scene? The offset should move the object in its local axes.

Thanks!
Mariano.

**Comment by ababak** [comment]
Hi Mariano,

Here's the scene I've been using.

Thanks!

Regards,
Andrey.

![curve_array_test](https://cloud.githubusercontent.com/assets/11334363/13857873/9189263e-ec84-11e5-9767-c001be7e9a7b.jpg)
[curve_array_test.mb.zip](https://github.com/mmerchante/instanceAlongCurve/files/178506/curve_array_test.mb.zip)

**Comment by mmerchante** [comment]
Hi ababak!

Yup, it seems I was missing some additional operations in the code. I've updated it, and now should be working! Note that in chain mode it will not be continuous.

It is now fixed in [861be47f2357d9792a469a21f1d5e11b4bb26802](https://github.com/mmerchante/instanceAlongCurve/commit/861be47f2357d9792a469a21f1d5e11b4bb26802)

**Comment by ababak** [comment]
Great, thanks!
